### ISSUE TITLE
bug: fix display flex on Dashboard

### ISSUE THREAD

**Issue by OmarIthawi** [nelc/futurex-theme#48]
```css
.dashboard {
    display: flex; // !important??
}

.dashboard .side-container {
    padding: 66px 20px 20px 40px;  // !important??
}
```

Fixes are needed in the LMS overrides.

Needed to look as two columns:

![Image](https://github.com/user-attachments/assets/7a06a329-bc00-44e7-8a5f-d3df8aeda256)
